### ISSUE TITLE
bwah

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/PyScript-Docs#1]
this is a super good idea, but I think this would be better implemented in react.js?

Tell me if I am wrong.

**Comment by kokonut27** [comment]
Ur right, so i'm currently making this in react.js. However, I am having issues with hosting it...

**Comment by darkdarcool** [comment]
I can maybe help.

**Comment by darkdarcool** [comment]
React is weird sometimes

**Comment by kokonut27** [comment]
okie, ill invite you later on tmrw  (im busy rn)

**Comment by darkdarcool** [comment]
K cool

**Comment by darkdarcool** [comment]
@JBYT27, can you inv me to the repl for this?

**Comment by kokonut27** [comment]
Sorry, but i've already fixed this, and I want to work on this by myself (sorry again). However, if I do need help, or if you want to help, could you leave pull requests? (I already have invited you to github tho, so...)

**Comment by darkdarcool** [comment]
k, kewl.

**Comment by darkdarcool** [comment]
also @JBYT27, maybe consider getting a vercal account, then putting this repo on vercal, so you have a domain better than replit? It's just an idea and the website will self update its self on push. Then in like 2-3 min the website is updated(tho if you put in your own domain it takes like an hour).

**Comment by kokonut27** [comment]
Hmm, ok! But just telling you, the website doesnt run on replit domain, it opens a new window in mozilla firefox, and then has the domain as localhost:3000, and it shows the react website. idk why its doing that, but it works!

**Comment by darkdarcool** [comment]
Local host is the only way react can show it to you without you putting this code on a software that can push it to a website for you. Luckily, vercel is a **WEBSITE** that can do that for you!

**Comment by kokonut27** [comment]
Hm. ~~Seems like ur sponsering vercel lmao (jk, lame joke).~~ okie, ill ask my parents if i can make an account! Thanks for mentioning this to me :D

**Comment by darkdarcool** [comment]
No, their not sponsoring me. But it is a good platform!

**Comment by kokonut27** [comment]
lol okie

**Comment by darkdarcool** [comment]
@JBYT27 also it is a lame joke

**Comment by kokonut27** [comment]
LOL

**Comment by darkdarcool** [comment]
@JBYT27, maybe consider putting links to pages rather than just putting shortcuts to one part of the page?

**Comment by kokonut27** [comment]
Hmmm, maybe? Thanks for suggestion!

**Comment by darkdarcool** [comment]
k kewl @JBYT27
