### ISSUE TITLE
Hosting Issue

### ISSUE THREAD

**Issue by kokonut27** [JBYT27/PyScript-Docs#2]
Hello coders!

I'm making this react.js docs, which is actually pretty neat (for me lol), but the hosting isn't working at all. I'm trying to host the website, but it just loads and loads, which doesn't really help at all. So if you guys could help me with this, I would be very glad!

Thanks!
- JB

**Comment by darkdarcool** [comment]
@JBYT27, react is very slow to start. You may wanna just start it and leave it alone for like 5 - 10 min(most of the time it's shorter). Then put always on on it so you don't have to keep loading it!

**Comment by kokonut27** [comment]
Ok, thanks! And it's fixed now! :)

**Comment by darkdarcool** [comment]
noice.
