### ISSUE TITLE
React App Multiple Pages

### ISSUE THREAD

**Issue by kokonut27** [JBYT27/PyScript-Docs#3]
Hello there!

I've been trying to add multiple pages to the docs, but I've been having some trouble, so could you guys help?

Thanks!

> For more info, comment below and ping me ;)

**Comment by iop3** [comment]
hmm...looks like people are not responding... (dont ask me i have no idea about reactjs). here's a tip to get people to answer @JBYT27. Just ~~PING~~ them. @darkdarcool  (<-- u know how to solve this issue right dark?)

**Comment by kokonut27** [comment]
lol okie xD

**Comment by darkdarcool** [comment]
Hi I probably do

**Comment by kokonut27** [comment]
lol, ok

**Comment by darkdarcool** [comment]
I can get on in 20 min

**Comment by darkdarcool** [comment]
i can get on now

**Comment by darkdarcool** [comment]
uhhh, you on JB

**Comment by iop3** [comment]
prob he busy :/

**Comment by darkdarcool** [comment]
ah ok. Hey, can you beta test something for me?

**Comment by darkdarcool** [comment]
hey @iop3, can you beta test something for me?

**Comment by kokonut27** [comment]
Uh @darkdarcool, could you help me with it? Like some code ideas? or etc?
I'm not gonna be avail rn, but just asking for some code or stuff.
Or I can just invite you. Just let me know :)

**Comment by darkdarcool** [comment]
Ok, you can inv

**Comment by kokonut27** [comment]
got it, ill do it tmrw or later on today ;)

**Comment by darkdarcool** [comment]
okie!

**Comment by darkdarcool** [comment]
can you invite me now?

**Comment by kokonut27** [comment]
sure, sry, just saying i wont be on

**Comment by kokonut27** [comment]
@darkdarcool, I just invited you. :D

**Comment by darkdarcool** [comment]
im on, lemme see what I can do

**Comment by kokonut27** [comment]
Closing
